FUNCTION(SET_PRECOMPILED_HEADER target pch_header pch_source)
	SET_TARGET_PROPERTIES(${target} PROPERTIES COMPILE_FLAGS "/Yu\"${pch_header}\"")
	SET_SOURCE_FILES_PROPERTIES(${pch_source} PROPERTIES COMPILE_FLAGS "/Yc\"${pch_header}\"")
ENDFUNCTION(SET_PRECOMPILED_HEADER)
